# Preprocess bmw.csv

### 1.0. Setup imports + project path

In [17]:
import sys
from pathlib import Path

# Add repo root so `import src...` works in notebooks
PROJECT_ROOT = Path.cwd().parents[0]  # notebooks/ -> repo root
sys.path.append(str(PROJECT_ROOT))

import pandas as pd

### 2.0. Load raw data

In [18]:
from src.config import DATA_RAW
from src.preprocessing import load_raw

df_raw = load_raw(DATA_RAW)
df_raw.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,5 Series,2014,11200,Automatic,67068,Diesel,125,57.6,2.0
1,6 Series,2018,27000,Automatic,14827,Petrol,145,42.8,2.0
2,5 Series,2016,16000,Automatic,62794,Diesel,160,51.4,3.0
3,1 Series,2017,12750,Automatic,26676,Diesel,145,72.4,1.5
4,7 Series,2014,14500,Automatic,39554,Diesel,160,50.4,3.0

### 3.0. Basic overview

In [19]:
df_raw.shape, df_raw.columns.tolist()

((10781, 9),
 ['model',
  'year',
  'price',
  'transmission',
  'mileage',
  'fuelType',
  'tax',
  'mpg',
  'engineSize'])

### 4.0. Data types + missing values

In [20]:
display(df_raw.dtypes)

missing = df_raw.isna().sum().sort_values(ascending=False)
missing[missing > 0]

model               str
year              int64
price             int64
transmission        str
mileage           int64
fuelType            str
tax               int64
mpg             float64
engineSize      float64
dtype: object

Series([], dtype: int64)

### 5.0. Quick stats

In [21]:
df_raw.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
model,10781,24,3 Series,2443,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,10781.0,NaN,NaN,NaN,2017.078935,2.349038,1996.0,2016.0,2017.0,2019.0,2020.0
price,10781.0,NaN,NaN,NaN,22733.408867,11415.528189,1200.0,14950.0,20462.0,27940.0,123456.0
transmission,10781,3,Semi-Auto,4666,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mileage,10781.0,NaN,NaN,NaN,25496.98655,25143.192559,1.0,5529.0,18347.0,38206.0,214000.0
fuelType,10781,5,Diesel,7027,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tax,10781.0,NaN,NaN,NaN,131.702068,61.510755,0.0,135.0,145.0,145.0,580.0
mpg,10781.0,NaN,NaN,NaN,56.399035,31.336958,5.5,45.6,53.3,62.8,470.8
engineSize,10781.0,NaN,NaN,NaN,2.167767,0.552054,0.0,2.0,2.0,2.0,6.6

### 6.0. Apply cleaning and compare

In [22]:
from src.preprocessing import basic_clean

df_clean = basic_clean(df_raw)

print("Raw shape:", df_raw.shape)
print("Clean shape:", df_clean.shape)

df_clean.head()

Raw shape: (10781, 9)
Clean shape: (10781, 9)

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,5 Series,2014,11200,Automatic,67068,Diesel,125,57.6,2.0
1,6 Series,2018,27000,Automatic,14827,Petrol,145,42.8,2.0
2,5 Series,2016,16000,Automatic,62794,Diesel,160,51.4,3.0
3,1 Series,2017,12750,Automatic,26676,Diesel,145,72.4,1.5
4,7 Series,2014,14500,Automatic,39554,Diesel,160,50.4,3.0

### 7.0. Sanity check

In [23]:
from src.config import TARGET_COL

df_clean[TARGET_COL].describe()

count     10781.000000
mean      22733.408867
std       11415.528189
min        1200.000000
25%       14950.000000
50%       20462.000000
75%       27940.000000
max      123456.000000
Name: price, dtype: float64

In [24]:
df_clean.sort_values(TARGET_COL, ascending=False).head(10)

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
3638,2 Series,2015,123456,Semi-Auto,33419,Diesel,20,68.9,2.0
5362,M4,2016,99950,Automatic,771,Petrol,300,33.2,3.0
2909,M4,2017,89990,Semi-Auto,1336,Petrol,145,33.2,3.0
4776,M5,2019,89900,Semi-Auto,2269,Petrol,145,24.1,4.4
1813,8 Series,2019,88980,Semi-Auto,88,Petrol,145,24.4,4.4
721,8 Series,2019,84898,Semi-Auto,3185,Petrol,145,24.4,4.4
5877,M5,2019,81140,Semi-Auto,551,Petrol,145,24.1,4.4
6115,8 Series,2020,79991,Semi-Auto,151,Diesel,145,26.7,3.0
7024,X7,2020,79566,Semi-Auto,1000,Petrol,145,24.8,3.0
2602,X7,2020,78490,Semi-Auto,4919,Diesel,145,31.4,3.0